GET http://localhost:3001/users

###

GET http://localhost:3001/users/6516c9f714d29774a8721a8a

###

POST http://localhost:3001/users
Content-Type: application/json

{
    "name" : "David",
    "eMail" : "justincalle@outlook.de",
    "password" : "123123"
}

###

PATCH http://localhost:3001/users/6521c327c0723fc6fcf4185d
Content-Type: application/json

{
    "name": "Hercules"
}

###
DELETE http://localhost:3001/users/